server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vote_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    port: 25
    protocol: smtp
    username: 1093805126@qq.com
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
mybatis:
  type-aliases-package: com.two.vote.entity
  mapper-locations: classpath:mapper/*Mapper.xml
